camera:
  m:
    - [505.24537524391866, 0.0, 324.5096286632362]
    - [0.0, 505.6456651337437, 233.54118730278543]
    - [0.0, 0.0, 1.0]
  d: [-0.07727407195057368, -0.047989733519315944, 0.12157420705123315, -0.09667542135039282]
  record: true
  fps: 2.5
  record_only_after_action: false
  save_images_individually: true

experiment:
  name: "backgammon"
  robot_idx: "robot21"
  timeout_between_experiments: 2.0
  time_between_orders: 2.5
